# Generated by Django 5.1.4 on 2024-12-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='composition',
            field=models.TextField(blank=True, null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='food',
            name='recipe_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на рецепт'),
        ),
    ]
